[package]
name = "sjs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "*"
deno_runtime = "*"
tokio = { version = "1.28.1", features = ["full"] }
clap = "2.33.3"
panic-message = "0.3.0"
backtrace = "0.3.64"

[build-dependencies]
deno_core = "*"
deno_runtime = "*"

[patch.crates-io]
deno_core = { path = "../deno_core/core" }
deno_runtime = { path = "../deno/runtime" }