[package]
name = "sjs"
version = "0.1.0"
edition = "2021"
authors = ["Trin Wasinger"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "*"
deno_runtime = "*"
tokio = { version = "1.28.1", features = ["full"] }
clap = { version = "4.5.0", features = ["cargo"] }
panic-message = "0.3.0"
backtrace = "0.3.64"
velcro="0.5.4"
home="0.5.9"

[build-dependencies]
deno_core = "*"
deno_runtime = "*"

[patch.crates-io]
deno_core = { path = "../deno_core/core" }
deno_runtime = { path = "../deno/runtime" }